### ISSUE TITLE
add support for um01 device

### ISSUE THREAD

**Issue by nikolaus-online** [ycardon/gigaset-elements-proxy#16]
Hey man,

first of all, thank you very much for your effort and your nice Proxy! I've used it for several weeks now on my openhab Pi without any problems.

Now I have migrated it to a Ubuntu-Server and recreated the service. But it seems not to work when an Item changes its state. Whenever I initialize it, it will work correctly - but when the state of an item changes, it throws an error.

`Sep 24 21:49:20 openhabian node[4518]: [Tue Sep 24 2019 21:49:20] [LOG]    acquired event: {"id":"1bac04c426e8030c2dde739b999da8868961c398","state":"ok","ts":"1569354557723","type":"open"
Sep 24 21:49:20 openhabian node[4518]: [Tue Sep 24 2019 21:49:20] [LOG]      event dropped: unhandled event type: um01`

Can you point me in the right direction?

**Comment by ycardon** [comment]
Well it seems that you have a kind of equipment `um01` that is new to me (you can check the list of supported devices in the README.md table).

I can do some changes if you want but you'll have to tell me more: extract some samples of these events, get the device description... and do some testings because I will be blind.

Meanwhile you can try to change the `allow_unknown_events` to true in the `config/default.yaml` file.

**Comment by ycardon** [comment]
you can refer to https://github.com/ycardon/gigaset-elements-proxy/issues/11 issue to get an idea of what informations are needed.

**Comment by nikolaus-online** [comment]
Hey ycardon,

it seems to be related to the service I generated for it. When I run the sh from the terminal it works without any complaint. It wasn't any problem on my raspberry, it seems to be a problem using ubuntu.

**Comment by nikolaus-online** [comment]
> Well it seems that you have a kind of equipment `um01` that is new to me (you can check the list of supported devices in the README.md table).

Nah, it's a simple window sensor I used for testing. And it worked flawlessly until I migrated the system to ubuntu.

**Comment by ycardon** [comment]
So it is outputting the same `event dropped: unhandled event type: um01` message whenever ANY states changes on ANY device, right ?

Apart from this message, do you have some device working ?

1. could you try switch the `allow_unknown_events|` to true in the `config/default.yaml` file ? do you see this message again ?
2. could you point to the `<my server>:port/api/v1/me/basestations` URL to see the RAW gigaset API describing all your devices. Is there a um01 type device ?

My guess is that:
- you already had this message on your RPi but you didn't see it because everything was working (it's an informative message : you have a device type I don't recognize)
- and you have an other problem elsewhere

Of course I can be wrong, please provide me more info.

**Comment by ycardon** [comment]
second reading : 
> When I run the app.js from the terminal it works without any complaint

now this is strange... maybe your service does not start in the correct directory. Do you have any authentication errors in the firsts steps ?

**Comment by ycardon** [comment]
third reading :) 
> Whenever I initialize it, it will work correctly - but when the state of an item changes, it throws an error.

could you get the corresponding event on the `<my server>:port/api/v2/me/events` RAW gigaset API ?

**Comment by ycardon** [comment]
can I close this issue ?

**Comment by ycardon** [comment]
same as https://github.com/ycardon/gigaset-elements-proxy/issues/17, now corrected.
