### ISSUE TITLE
Feature Request: support of Gigaset Thermostate “ts01“

### ISSUE THREAD

**Issue by Pe-MaKer** [ycardon/gigaset-elements-proxy#20]
I know that the currently used API do not support setting values.
Is there any chance to get support for the Thermostate of Gigaset Elements?

Or should I connect a DECT Thermostate to my Fritzbox and throw the Gigaset one away (because it is not open to connect anything apart of the Elements Base)?

**Comment by ycardon** [comment]
Sorry for the lag in the answer... Well, as you said, I haven’t implemented what’s needed in order to set values and I haven’t planned to :(
Nevertheless, if there are some events that you might think useful in the thermostat, I can try to add them, tell me.
On my side, I have a software thermostat using home-assistant and some DIY temperature sensor : it’s much more versatile as any proprietary solution.

**Comment by Pe-MaKer** [comment]
Thank you so much for your reaction. I well understand that much additional effort would be needed to send values.
So I've come to the point of retiring the Gigaset thermostat and instead using DECT-ULE HAN-FAN compatible thermostats and controlling them via the AVM Fritz box. Gigaset Elements will only be responsible for the sensors.

Thanks for your support so far and hopefully also in the future.
