### ISSUE TITLE
Gigaset Cameras 

### ISSUE THREAD

**Issue by acs-lux** [ycardon/gigaset-elements-proxy#29]
Hi. 
This is a great add-on.
Is there any more info you can give for accessing the camera video locally? The documentation says details need to be in a config file but which details, how and what config file? 
Would be the icing on the cake to be able to get a live video from my cam in hassio.
Many thanks for your work.

**Comment by h4nc** [comment]
Hi,

I don't have Gigaset camaras, so I can't help with the configuration.

However I can help with the confusion about the config file. Seems like you are using the gigaset elements proxy as an add-on in hassio. 

In this case the configuration is done directly in the add-on section (in the Configuration tab). So you don't need to find that config file (which you would need to find if you used install [option 2 or 3](https://github.com/ycardon/gigaset-elements-proxy#option-2---from-git)).

**Comment by ycardon** [comment]
Hello,

The (brief) instructions are in that config file : https://github.com/ycardon/gigaset-elements-proxy/blob/master/config/default.yaml

```
# camera id (found with /api/v1/me/cameras)
camera_id: 'xxxx'

# camera local IP (used for local streaming)
camera_ip: 'xxx.xxx.xxx.xxx'

# camera local password
# $> echo –n "LUCKOTVF<MAC-address-reverse-order-uppercase-nocolon>YCAMVF" | base64
# or discover it by sniffing your network while changing your camera config in the mobile app:
# $> ssh <router> "tcpdump -i lbr0 -s0 -w - host <camera_ip>" | wireshark -k -i -
camera_password: '****'
```

I broke my camera so I hope it still works... The camera password is hardcoded with the Mac address of you camera.

for instance, if your mac address is `ab:cd:ef:gh:ij` then the password is
- either LUCKOTVF**JIHGFEDCBA**YCAMVF 
- or LUCKOTVF**IJGHEFCDAB**YCAMVF (I don't remember)

Then you have to encode it in Base64

**Comment by stjones-dev** [comment]
Hi,Ok many thanks. So this is how its configured in the hassio haddon?I'll give it a go and let you know how I get on.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Yann Cardon <notifications@github.com> Date: 16/05/2020  16:36  (GMT+01:00) To: ycardon/gigaset-elements-proxy <gigaset-elements-proxy@noreply.github.com> Cc: stjones-dev <stjones@pt.lu>, Author <author@noreply.github.com> Subject: Re: [ycardon/gigaset-elements-proxy] Gigaset Cameras  (#29) 

Hello,

The (brief) instructions are in that config file : https://github.com/ycardon/gigaset-elements-proxy/blob/master/config/default.yaml

# camera id (found with /api/v1/me/cameras)

camera_id: 'xxxx'



# camera local IP (used for local streaming)

camera_ip: 'xxx.xxx.xxx.xxx'



# camera local password

# $> echo –n "LUCKOTVF<MAC-address-reverse-order-uppercase-nocolon>YCAMVF" | base64

# or discover it by sniffing your network while changing your camera config in the mobile app:

# $> ssh <router> "tcpdump -i lbr0 -s0 -w - host <camera_ip>" | wireshark -k -i -

camera_password: '****'



I broke my camera so I hope it still works... The camera password is hardcoded with the Mac address of you camera.

for instance, if your mac address is ab:cd:ef:gh:ij then the password is



either LUCKOTVFJIHGFEDCBAYCAMVF

or LUCKOTVFIJGHEFCDABYCAMVF (I don't remember)



Then you have to encode it in Base64



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ycardon/gigaset-elements-proxy/issues/29#issuecomment-629655697",

"url": "https://github.com/ycardon/gigaset-elements-proxy/issues/29#issuecomment-629655697",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by stjones-dev** [comment]
Hi. I tried both ways. VLC wont open either the local or remote live views. Links dont open anything and browser gives an error. What am I missing? How did you actually view the video?

**Comment by ycardon** [comment]
I've checked back in the code

https://github.com/ycardon/gigaset-elements-proxy/blob/3b30e3077ff3c05da6fa9e1692d076c44f32f662/src/web-server.ts#L16-L31

You've got (at least, "you had" when I coded it) two options to get camera stream:
- `/live` which get it from the Gigaset server
  - there you need your normal Gigaset user and password + your camera device id
  - it is returning a `RSTP` stream : you can copy the returned URL in VLC for instance

- `/live-local` witch get the stream from your local network 
  - there you need your camera password computed with the mac address, as stated in this [vulnerability audit](https://team-sik.org/sik-2016-045/))
  - it is an `mjpeg` stream that you should be able to open inside your browser.

To test the second one, you can just call the following url in your browser:
```
http://admin:<CAM_PASSWORD>@<CAM_IP>/stream.jpg
```
If it's not working, that means that Gigaset have fixed the vulnerability (which is a good thing)

**Comment by stjones-dev** [comment]
Perfect, local works for me but not live from gigaset server. I'm a happy man now.

**Comment by KubaDavid** [comment]
> Perfect, local works for me but not live from gigaset server. I'm a happy man now.

@acs-lux Is it still working for you? I've tried all possible combinations but I just can't access local stream...

**Comment by acs-lux** [comment]
My camera died. I use Tp-Lnk c200 now.
