### ISSUE TITLE
Sensordata Home Assistant reboot

### ISSUE THREAD

**Issue by h4nc** [ycardon/gigaset-elements-proxy#5]
Hi,

as a mentioned in the other thread I have another idea to improve this project. 

As you no at a reboot of home assistant you will loose the sensor data. E.g an open window that was shown open before will be closes after the reboot, but in reality it is still open.

The idea would be to push a mqtt event from home assistatn when it starts up to a certain topic.

The gigaset-proxy would than have to listen to this topic and if its status changes to true,  it has to send all the known sensor data again in the known topics. This way all sensorvalues would be the right ones (if the proxy servers runs long enough, so that it had a chance to collect this data)

I know you advices to use a restful sensor for this, but I don't think thats its possible to two different sensor data's to one sensor (mqtt and restful). 

what do you say about this idea? Is it makeable without to much effort and spending to much time with it?

**Comment by ycardon** [comment]
Seems like a good idea (in fact I've never had any stability problem with the solution so I rarely reboot except for system updates): check the latest version, it's working fine on my setup.

Now you HAVE to look at the source code, and start to invest in development :P

**Comment by h4nc** [comment]
I don’t think that I can do that. I think I will see how all runs. Until now everything seems to be fine.

Thanks!

**Comment by ycardon** [comment]
> you run your gigaset-elements-proxy on the same system as home assistant

Nope, I'm running ``gigaset-elements-proxy`` and ``mosquito`` (mqtt broker) on the same server (Archlinux on RPi). ``home-assistant`` runs in docker on a NAS so I don't use ``hass.io``.

For your use case:
1. you can send SSH commands remotely using https://www.home-assistant.io/components/shell_command/. If you do so, do not restart the server, just the service ``sudo systemctl restart gigaset-server@pi.service``
2. I've added an API ``http://myserver:3000/force-refresh``so that you can force a refresh of the sensors actual values without restarting the service. Use it with https://www.home-assistant.io/components/rest_command/

**Comment by h4nc** [comment]
Option 2 is even better, thanks for implementing this. This tool gets better and better. 

I have to say it ... I have another idea. Personally I don't need this because everything I wanted works just fine now for me.
If you'd like to reach even more people to use your project than an integration or an app add-on in hass.io would be great. As home assistant gets more popular (rank 9 in top 10 open source projects), more and more noobs like me would like to have features like this. It just another idea, had to tell you ;-)

OT:
Bye the way, I did not get a notification that you changed some thing in this project (force-refresh) altough I watch the project. Do you know why? Is there a way to get informed about your updates?

**Comment by h4nc** [comment]
Maybe you want to add this as  an example

in configuratiion.yaml:
```
rest_command:
  gigasetproxy_request:
    url: 'http://myserver:3000/force-refresh'
```

in automation.yaml
```
- alias: Gigaset - MQTT-Event Refresh bei Restart
  initial_state: 'on'
  trigger:
    - event: start
      platform: homeassistant
  action:
    - delay: 00:00:10 # don't know if this is necessary, just do give it some time
    - service: rest_command.gigasetproxy_request
```

**Comment by ycardon** [comment]
Thanks for the examples, I've updated the project but I couldn't test it because I'm not at home.

Having a hass.io module is a great idea and it does not seem very complicated to do. I could consider doing it in the future (but not right now, I don't have any hass.io platform for testing). I'd also be happy if someone does it using this project as a base (for instance by using the npm package that I keep up to date).

On the other hand, keeping this project not so wide-known is also very ok to me: I did publish it two years ago on the semi-official Gigaset Elements group on Google+ and all my posts have been deleted by the (Gigaset GmbH ?) moderator. At that time I didn't know what to think...

**Comment by h4nc** [comment]
> On the other hand, keeping this project not so wide-known is also very ok to me: I did publish it two years ago on the semi-official Gigaset Elements group on Google+ and all my posts have been deleted by the (Gigaset GmbH ?) moderator. At that time I didn't know what to think...

I see... ok so than maybe you are right and its better to keep it "not so wide-known". Would be too bad if someone from Gigaset sees this as a security issue (or something like that) and changes something on their side to eliminate this project.

Don't know if that would be possible (because I don't know how you get the data from gigaset) ... but you know it ;-)

However, most probably guys that like to have that project running and are not able will comment here or on the ha topic. I will also be glad to help, if there are noob questions on how to install everything.

**Comment by ycardon** [comment]
You completely got my point :)

It won't be a security issue: we're not doing anything different from what's done in the web application. But there are some reverse engineering on an unpublished API (which is legal but have to be motivated) and a possible hammering on Gigaset servers if your ``check_events_interval`` is too low.

> I will also be glad to help, if there are noob questions on how to install everything

Right ! And take the "hard path" makes you learn new useful skills (for instance, you now know how to manage services inside raspbian and make your own), if you were not in that DIY spirit, you would have bought a complete Apple Homekit ecosystem or an already made SmartHome box (even if they are hundred miles less powerful than HA :D)

**Comment by h4nc** [comment]
yes leared a lot, thanks for your patience.

>  if your check_events_interval is too low.
I kept it at your default rate, so hopefully we are not hammering to much 🗡 

> (even if they are hundred miles less powerful than HA :D)

I would say at leeeast a million miles ;-)

Next project will be to make my plants smart. Check out "xiaomi miflora" (at aliexpress or something like that) if you are also interested in doing that.
